name: Modrinth App release
on:
  workflow_dispatch:
    inputs:
      version-tag:
        description: Version tag to release to the wide public
        type: string
        required: true
      release-notes:
        description: Release notes to include in the Tauri version manifest
        type: string
        required: true

jobs:
  release:
    name: Release Modrinth App
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Download Modrinth App artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: theseus-build.yml
          workflow_conclusion: success
          event: push
          branch: ${{ inputs.version-tag }}
          use_unzip: true
      - name: Debug artifacts
        run: ls -lRa
